### PR TITLE
More complicated methods

### PR DESCRIPTION
**Pull request by martinremis**
## Summary
* Add search endpoints for users and books
## Trello card
https://trello.com/c/HnMbz2mk/25-agregar-m%C3%A9todos-m%C3%A1s-complejos-a-los-repositorios

### CODE REVIEW

**Review by rodrigofranc — COMMENTED** [review]
Always add tests for new functionality

**Comment by martinremis** [comment]
> Always add tests for new functionality

Done for #16, #15 and #14.

**Review by rodrigofranc — APPROVED** [review]

**Review by rabinovichm — CHANGES_REQUESTED** [review]
You should also test the new methods added in the repositories, because right now you are not testing the new behaviour, you are mocking it to test the controller.

**Review by rabinovichm — APPROVED** [review]
Nice! 😄

**Pull request merged**
